### ISSUE TITLE
Dogs sometimes lose their stats

### ISSUE THREAD

**Issue by Jukys111** [DoggyCraft/MyDog#44]
I configured the plugin on my server to scale dogs to level 20. However, after they reach this level, they sometimes lose all their stats and revert to 20 HP and 4 dmg. I have no idea what causes it, attack, kill, or passing some xp threshold? I always leveled my dogs in skeleton farm and then went to the Nether. The issue always happened in the Nether, however this could be only an accident and it would happen either way. Maybe it could happen even before the max level, I simply have no idea what is going on. One dog actually lost his stats and recovered them a few minutes after... I'm just lost lol.

**Comment by HeroGamers** [comment]
With the way that the stats are currently being applied to the dogs, they get applied everytime the dog loads in (since Minecraft has a thing with removing stats that don't fit the mob, I guess).
I'll take a look into it though, but I have a lot of other stuff that I'm currently working on ATM, so I can't give any ETA.
