### ISSUE TITLE
The puppy's name disappears and appears as Wolf.

### ISSUE THREAD

**Issue by excaliburkim** [DoggyCraft/MyDog#65]
Hello.
Thank you for developing a great program.
I'm having a little problem.
I have 3 puppies.
One day, 1 puppy doesn't see the name and the name appears to be Wolf.
It is so sad that the well-raised puppy lost his name and became a regular wolf.
Oddly, '/mydog list' shows all 3 dog names just fine.
I am using the latest version.
Please check!
thank you

**Comment by HeroGamers** [comment]
Hi there,
Thanks for the bug report; however, I have nowhere near enough information to try and reproduce this issue myself, and I haven't heard others with the same issue.

What happens if you right-click the dog?
What if you run the comehere command?
Is it the nametag above the dog that is gone, and turned into "Wolf"? The plugin doesn't change any names into "Wolf", ever. Unless renamed by a player.
Maybe you have some other plugins causing issues with the dog names?

Until any more information is added, I will be closing the issue.

Cheers,
Hero
